### ISSUE TITLE
Licensing violations in Krypton related to code derived from the Velocity project

### ISSUE THREAD

**Issue by astei** [KryptonMC/Krypton#40]
### Description

The Krypton project contains code that violates the licensing terms of the Velocity project. Examples:

### `KryptonEventManager.kt`

The [`KryptonEventManager.kt`](https://github.com/KryptonMC/Krypton/blob/cc04d317f695c75c8439fc2fade6dfa68c5ca3d1/server/src/main/kotlin/org/kryptonmc/krypton/plugin/KryptonEventManager.kt) file is a mechanical translation of the [`VelocityEventManager.java`](https://github.com/VelocityPowered/Velocity/blob/c747120b20be1853ee02e7b2b67871249a88aa6d/proxy/src/main/java/com/velocitypowered/proxy/plugin/VelocityEventManager.java) from Java to Kotlin. This file is (currently) dual-licensed under MIT and GPLv3, but given its inclusion in a GPLv3 project, I assume you are using this under the GPLv3.

Since you have elected to use this file under GPLv3, there are some important requirements you have to follow, none of which were taken:

* You must disclose the changes you made to this file (in this case, a mechanical translation of the code from Java to Kotlin)
* Include the original copyright disclaimer from the Velocity project
* Include the original source of the material (for my purposes, a link in the README and on your website to https://velocitypowered.com as appropriate would be sufficient).

### The plugin loading system

[This commit](https://github.com/KryptonMC/Krypton/commit/78fc69b8a50c02fe9aadd98ef595962ba3ceefc0) wholesale copies code from Velocity's own plugin loading system and has all of the same violations as above.

### Other bits and pieces

* [This code is lifted from the Mojang server directly](https://github.com/KryptonMC/Krypton/blob/cd4ea0784c446b861b91d1f72331f1bc6c801ef2/server/src/main/kotlin/org/kryptonmc/krypton/util/bytebufs.kt#L117). This is arguably worse since you're including closed-source, proprietary code in what's supposed to be an open-source project.
* A similar story for basic things like [reading strings](https://github.com/KryptonMC/Krypton/blob/cd4ea0784c446b861b91d1f72331f1bc6c801ef2/server/src/main/kotlin/org/kryptonmc/krypton/util/bytebufs.kt#L138) and the [scheduler mechanism](https://github.com/KryptonMC/Krypton/blob/master/server/src/main/kotlin/org/kryptonmc/krypton/scheduling/KryptonScheduler.kt), all of which were lifted from Velocity without following the licensing terms.

## Conclusion

I did not file this issue to scare you away from including code from other projects - quite the contrary, sometimes it strengthens your project and allows you to move onto more interesting things without having to reinvent the fundamentals. But if you do so, you are _obligated_ to at least pay attention to the licensing terms under which that code is made available to you.

**Comment by BomBardyGamer** [comment]
Hey Tux, thanks for reporting these violations. As you know from our Discord conversation, I was not aware of the appropriate practices for copying and creating derivative works of licensed code, which was my fault for not properly reading the license terms, and which I have already apologised for.

All of the mentioned Velocity license violations should be fixed by [this commit](https://github.com/KryptonMC/Krypton/commit/91b1adba3e91315e24f360a32019c4e43e6fb6d8). As for the proprietary code usage, this issue extends much further than just the single file you mentioned, which is why I will be working to rewrite all of the proprietary code from scratch, to remove this issue.

Thank you for spending your time writing out this issue, I very much appreciate your effort.
